# Generated by Django 3.2.4 on 2022-08-28 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_img', models.ImageField(upload_to='banner_image/')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
                ('link', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('c_img', models.ImageField(upload_to='category_image/')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img1', models.ImageField(null=True, upload_to='product_image/')),
                ('img2', models.ImageField(null=True, upload_to='product_image/')),
                ('description', models.CharField(default='', max_length=400)),
                ('about', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('offer', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rbidapp.category')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbidapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=100)),
                ('p_catog', models.CharField(default='', max_length=100)),
                ('p_price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbidapp.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ProductSeller',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=200)),
                ('p_img', models.CharField(default='', max_length=200)),
                ('p_id', models.PositiveIntegerField(default=0)),
                ('p_price', models.PositiveIntegerField(default=0)),
                ('p_qty', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='BidResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('qty', models.PositiveIntegerField()),
                ('img', models.CharField(default='', max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('about', models.TextField()),
                ('expiry', models.DateTimeField()),
                ('seller1_price', models.PositiveIntegerField()),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BidResult',
            },
        ),
        migrations.CreateModel(
            name='BidProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(default='', max_length=200)),
                ('b_img', models.CharField(default='', max_length=200)),
                ('b_about', models.TextField()),
                ('b_price', models.PositiveIntegerField(default=0)),
                ('b_qty', models.PositiveIntegerField()),
                ('b_expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BidProduct',
            },
        ),
        migrations.CreateModel(
            name='BidInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_price', models.PositiveIntegerField()),
                ('bs_product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rbidapp.bidproduct')),
                ('bs_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BidInfo',
            },
        ),
    ]
